<?php

/**
 * BaseBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $title
 * @property string $author
 * @property sfGuardUser $User
 * @property Doctrine_Collection $editions
 * 
 * @method integer             getUserId()   Returns the current record's "user_id" value
 * @method string              getTitle()    Returns the current record's "title" value
 * @method string              getAuthor()   Returns the current record's "author" value
 * @method sfGuardUser         getUser()     Returns the current record's "User" value
 * @method Doctrine_Collection getEditions() Returns the current record's "editions" collection
 * @method Book                setUserId()   Sets the current record's "user_id" value
 * @method Book                setTitle()    Sets the current record's "title" value
 * @method Book                setAuthor()   Sets the current record's "author" value
 * @method Book                setUser()     Sets the current record's "User" value
 * @method Book                setEditions() Sets the current record's "editions" collection
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBook extends Item
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('book');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Edition as editions', array(
             'local' => 'id',
             'foreign' => 'book_id'));
    }
}