<?php

/**
 * BaseTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $edition_id
 * @property integer $language_id
 * @property string $url
 * @property Edition $Edition
 * @property Language $Language
 * @property sfGuardUser $User
 * @property Doctrine_Collection $chapters
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getEditionId()   Returns the current record's "edition_id" value
 * @method integer             getLanguageId()  Returns the current record's "language_id" value
 * @method string              getUrl()         Returns the current record's "url" value
 * @method Edition             getEdition()     Returns the current record's "Edition" value
 * @method Language            getLanguage()    Returns the current record's "Language" value
 * @method sfGuardUser         getUser()        Returns the current record's "User" value
 * @method Doctrine_Collection getChapters()    Returns the current record's "chapters" collection
 * @method Translation         setUserId()      Sets the current record's "user_id" value
 * @method Translation         setEditionId()   Sets the current record's "edition_id" value
 * @method Translation         setLanguageId()  Sets the current record's "language_id" value
 * @method Translation         setUrl()         Sets the current record's "url" value
 * @method Translation         setEdition()     Sets the current record's "Edition" value
 * @method Translation         setLanguage()    Sets the current record's "Language" value
 * @method Translation         setUser()        Sets the current record's "User" value
 * @method Translation         setChapters()    Sets the current record's "chapters" collection
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTranslation extends Article
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('translation');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('edition_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => 255,
             ));


        $this->index('edition_id_language_id_UNIQUE', array(
             'fields' => 
             array(
              0 => 'edition_id',
              1 => 'language_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Edition', array(
             'local' => 'edition_id',
             'foreign' => 'id'));

        $this->hasOne('Language', array(
             'local' => 'language_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Chapter as chapters', array(
             'local' => 'id',
             'foreign' => 'translation_id'));
    }
}