<?php

/**
 * BaseSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $chapter_id
 * @property integer $number
 * @property Chapter $Chapter
 * 
 * @method integer getChapterId()  Returns the current record's "chapter_id" value
 * @method integer getNumber()     Returns the current record's "number" value
 * @method Chapter getChapter()    Returns the current record's "Chapter" value
 * @method Section setChapterId()  Sets the current record's "chapter_id" value
 * @method Section setNumber()     Sets the current record's "number" value
 * @method Section setChapter()    Sets the current record's "Chapter" value
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSection extends Article
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('section');
        $this->hasColumn('chapter_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('chapter_id_title_UNIQUE', array(
             'fields' => 
             array(
              0 => 'chapter_id',
              1 => 'title',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chapter', array(
             'local' => 'chapter_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}