<?php

/**
 * BaseEdition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $book_id
 * @property string $version
 * @property Book $Book
 * @property sfGuardUser $User
 * @property Doctrine_Collection $translations
 * 
 * @method integer             getUserId()       Returns the current record's "user_id" value
 * @method integer             getBookId()       Returns the current record's "book_id" value
 * @method string              getVersion()      Returns the current record's "version" value
 * @method Book                getBook()         Returns the current record's "Book" value
 * @method sfGuardUser         getUser()         Returns the current record's "User" value
 * @method Doctrine_Collection getTranslations() Returns the current record's "translations" collection
 * @method Edition             setUserId()       Sets the current record's "user_id" value
 * @method Edition             setBookId()       Sets the current record's "book_id" value
 * @method Edition             setVersion()      Sets the current record's "version" value
 * @method Edition             setBook()         Sets the current record's "Book" value
 * @method Edition             setUser()         Sets the current record's "User" value
 * @method Edition             setTranslations() Sets the current record's "translations" collection
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEdition extends Item
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('edition');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('book_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('version', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));


        $this->index('book_id_version_UNIQUE', array(
             'fields' => 
             array(
              0 => 'book_id',
              1 => 'version',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Book', array(
             'local' => 'book_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Translation as translations', array(
             'local' => 'id',
             'foreign' => 'edition_id'));
    }
}