<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle {

  public function setDescription($description) {
    $this->_set('description', $description);
    require_once dirname(__FILE__) . '/../../util/markdown.php';
    $description = htmlspecialchars($description, ENT_NOQUOTES, 'UTF-8', false);
    $description = Markdown($description);
    $this->setHtmlDescription($description);
  }

}
