<?php

/**
 * Book
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Book extends BaseBook {

  public function __toString() {
    return $this->getTitle();
  }

  public function getInactiveEditions(){
    return BookTable::getInactiveEditions($this->getId());
  }

  public function getEditions(){
    return BookTable::getEditions($this->getId());
  }

}
