<?php

/**
 * Chapter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chapter extends BaseChapter {

  public function __toString() {
    if ($this->getNumber() > 0 && $this->getNumber() < 100)
      return 'Chapter ' . $this->getNumber() . ' - ' . $this->getTitle();
    else
      return $this->getTitle();
  }

  public function getSections() {
    return ChapterTable::getSections($this->getId());
  }

  public function getNext() {
    return ChapterTable::getNext($this);
  }

  public function getPrevious() {
    return ChapterTable::getPrevious($this);
  }

}
