<?php

/**
 * Translation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Translation extends BaseTranslation {

  public function __toString() {
    if ($this->getTitle())
      return $this->getTitle();
    return $this->getEdition() . ' in ' . $this->getLanguage();
  }

  public function setUrl($value) {
    if (empty($value))
      $this->_set('url', null);
    else
      $this->_set('url', $value);
  }

  public function getChapters() {
    return TranslationTable::getChapters($this->getId());
  }

}
