<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bookeet
 * @subpackage model
 * @author     Peter Long  http://peterlong.info
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {

  public function getBooks() {
    return sfGuardUserTable::getBooks($this->getId());
  }

  public function getEditions() {
    return sfGuardUserTable::getEditions($this->getId());
  }

  public function getTranslations() {
    return sfGuardUserTable::getTranslations($this->getId());
  }

}
