newSuccess:
  stylesheets:    [ markitup/skin.css, markitup/markdown.css, tooltip/jquery.tooltip.css ]
  javascripts:    [ jquery-1.4.2.min.js, markitup/jquery.markitup.pack.js, markitup/markdown.js, tooltip/jquery.tooltip.min.js ]

